apiVersion: scaffolder.backstage.io/v1beta3
kind: Template

metadata:
  name: aws-rds-postgresql
  title: AWS RDS PostgreSQL
  description: Provision an AWS RDS PostgreSQL database using Terraform
  tags:
    - aws
    - rds
    - postgresql
    - database
    - terraform

spec:
  owner: user:guest
  type: infrastructure

  parameters:
    - title: RDS Configuration
      required:
        - databaseName
        - region
        - instanceClass
        - storage
        - environment
        - owner
        - dbPassword

      properties:
        databaseName:
          title: Database Name
          type: string
          description: Name of the PostgreSQL database instance

        region:
          title: AWS Region
          type: string
          description: AWS region where the database will be provisioned
          ui:field: AwsRegionPicker

        instanceClass:
          title: RDS Instance Class
          type: string
          description: RDS instance class
          default: db.t3.micro

        storage:
          title: Storage Size (GB)
          type: integer
          description: Allocated database storage
          default: 20
          minimum: 20

        environment:
          title: Environment
          type: string
          default: dev
          enum:
            - dev
            - test
            - staging
            - prod

        owner:
          title: Owner
          type: string
          description: Owner of the database

        dbUsername:
          title: Database Username
          type: string
          description: PostgreSQL master username
          default: postgres

        dbPassword:
          title: Database Password
          type: string
          description: Password for the PostgreSQL master user
          ui:field: Secret

  steps:
    - id: fetch
      name: Fetch Terraform Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          databaseName: ${{ parameters.databaseName }}
          region: ${{ parameters.region }}
          instanceClass: ${{ parameters.instanceClass }}
          storage: ${{ parameters.storage }}
          environment: ${{ parameters.environment }}
          owner: ${{ parameters.owner }}
          dbUsername: ${{ parameters.dbUsername }}
          dbPassword: ${{ parameters.dbPassword }}

    - id: publish
      name: Publish Repository
      action: publish:github
      input:
        repoUrl: github.com?owner=Abhi0312-eve&repo=${{ parameters.databaseName }}-rds-terraform
        description: Terraform generated by Backstage for AWS RDS PostgreSQL
        defaultBranch: main
        repoVisibility: public

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}

      - title: Terraform Workflow
        url: ${{ steps.publish.output.remoteUrl }}/actions
