name: Provision AWS S3

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Show GitHub Context
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Repository owner: $GITHUB_REPOSITORY_OWNER"
          echo "Ref: $GITHUB_REF"
          echo "Branch: $GITHUB_REF_NAME"
          echo "Event: $GITHUB_EVENT_NAME"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::982344023689:role/GitHubActionsTerraform
          aws-region: ${{ values.region }}

      - name: Verify AWS Identity
        run: aws sts get-caller-identity


      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Debug
        run: |
          terraform version
          terraform providers

      - name: Terraform Apply
        run: terraform apply -auto-approve


      - name: Save S3 Details
        run: |
          cat > s3-details.json <<EOF
          {
            "bucket_name": "$(terraform output -raw bucket_name)",
            "bucket_arn": "$(terraform output -raw bucket_arn)",
            "region": "$(terraform output -raw region)",
            "environment": "$(terraform output -raw environment)"
          }
          EOF

          cat s3-details.json

      - name: Show S3 Details
        run: |
          echo "================================"
          echo "S3 Provisioning Successful"
          echo "================================"
          echo "Bucket      : $(terraform output -raw bucket_name)"
          echo "ARN         : $(terraform output -raw bucket_arn)"
          echo "Region      : $(terraform output -raw region)"
          echo "Environment : $(terraform output -raw environment)"
          echo "================================"
