instanceName    = "${{ values.instanceName }}"
instanceType    = "${{ values.instanceType }}"
region          = "${{ values.region }}"
keyName         = "${{ values.keyName }}"
securityGroupId = "${{ values.securityGroupId }}"
