instanceName    = "${{ values.instanceName }}"
instanceType    = "${{ values.instanceType }}"
region          = "${{ values.region }}"
operatingSystem = "${{ values.operatingSystem }}"
owner           = "${{ values.owner }}"
