apiVersion: scaffolder.backstage.io/v1beta3
kind: Template

metadata:
  name: aws-ec2
  title: AWS EC2 Instance
  description: Provision an AWS EC2 Terraform project
  tags:
    - aws
    - ec2
    - terraform

spec:
  owner: user:guest
  type: infrastructure

  parameters:
    - title: Terraform Module
      required:
        - moduleVersion

      properties:
        moduleVersion:
          title: Module Version
          type: string
          description: Version of the internal AWS EC2 module
          ui:field: ModuleVersionPicker

    - title: EC2 Configuration
      required:
        - instanceName
        - region
        - instanceType
        - operatingSystem
        - owner

      properties:
        instanceName:
          title: EC2 Instance Name
          type: string

        region:
          title: AWS Region
          type: string
          description: AWS region where the EC2 instance will be provisioned
          ui:field: AwsRegionPicker

        instanceType:
          title: Instance Type
          type: string
          description: EC2 instance type to provision
          ui:field: AwsInstanceTypePicker

        operatingSystem:
          title: Operating System
          type: string
          description: Operating system / AMI to provision
          ui:field: AwsOperatingSystemPicker

        storageSize:
          title: Storage Size (GB)
          type: integer
          description: Root volume size in GB
          minimum: 1
          default: 20
          ui:field: ModuleStorageSizePicker

        owner:
          title: Owner
          type: string
          description: Owner of the EC2 instance

  steps:
    - id: fetch
      name: Fetch Terraform Template
      action: fetch:template
      input:
        url: https://github.com/Abhi0312-eve/iac-catalog/tree/aws-ec2-${{ parameters.moduleVersion }}/templates/aws-ec2/skeleton
        values:
          moduleVersion: ${{ parameters.moduleVersion }}
          instanceName: ${{ parameters.instanceName }}
          region: ${{ parameters.region }}
          instanceType: ${{ parameters.instanceType }}
          operatingSystem: ${{ parameters.operatingSystem }}
          storageSize: ${{ parameters.storageSize }}
          owner: ${{ parameters.owner }}


    - id: publish
      name: Publish Repository
      action: publish:github
      input:
        repoUrl: github.com?owner=Abhi0312-eve&repo=${{ parameters.instanceName }}-terraform
        description: Terraform generated by Backstage
        defaultBranch: main
        repoVisibility: public

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}

      - title: Terraform Workflow
        url: ${{ steps.publish.output.remoteUrl }}/actions
