apiVersion: scaffolder.backstage.io/v1beta3
kind: Template

metadata:
  name: aws-ec2
  title: AWS EC2 Instance
  description: Provision an AWS EC2 Terraform project
  tags:
    - aws
    - ec2
    - terraform

spec:
  owner: user:guest
  type: infrastructure

  parameters:
    - title: EC2 Configuration
      required:
        - instanceName
        - region
        - instanceType
        - operatingSystem
        - owner

      properties:
        instanceName:
          title: EC2 Instance Name
          type: string

        region:
          title: AWS Region
          type: string
          default: us-east-2
          enum:
            - us-east-1
            - us-east-2
            - us-west-2

        instanceType:
          title: Instance Type
          type: string
          default: t2.micro
          enum:
            - t2.micro
            - t3.micro
            - t3.small
 
        operatingSystem:
          title: Operating System
          type: string
          default: Amazon Linux 2023
          enum:
            - Amazon Linux 2023
            - Ubuntu 24.04

        owner:
          title: Owner
          type: string
          description: Owner of the EC2 instance

  steps:
    - id: fetch
      name: Fetch Terraform Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          instanceName: ${{ parameters.instanceName }}
          region: ${{ parameters.region }}
          instanceType: ${{ parameters.instanceType }}
          operatingSystem: ${{ parameters.operatingSystem }}
          owner: ${{ parameters.owner }}


    - id: publish
      name: Publish Repository
      action: publish:github
      input:
        repoUrl: github.com?owner=Abhi0312-eve&repo=${{ parameters.instanceName }}-terraform
        description: Terraform generated by Backstage
        defaultBranch: main
        repoVisibility: public

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
