apiVersion: scaffolder.backstage.io/v1beta3
kind: Template

metadata:
  name: aws-s3
  title: AWS S3 Bucket
  description: Provision an AWS S3 bucket using Terraform
  tags:
    - aws
    - s3
    - storage
    - terraform

spec:
  owner: user:guest
  type: infrastructure

  parameters:
    - title: S3 Configuration
      required:
        - bucketName
        - region
        - environment
        - owner

      properties:
        bucketName:
          title: S3 Bucket Name
          type: string
          description: Globally unique S3 bucket name
          pattern: '^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$'

        region:
          title: AWS Region
          type: string
          description: AWS region where the S3 bucket will be created
          ui:field: AwsRegionPicker

        environment:
          title: Environment
          type: string
          default: dev
          enum:
            - dev
            - test
            - staging
            - prod

        owner:
          title: Owner
          type: string
          description: Owner of the S3 bucket

        versioning:
          title: Enable Versioning
          type: boolean
          description: Enable S3 object versioning
          default: true

  steps:
    - id: fetch
      name: Fetch Terraform Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          bucketName: ${{ parameters.bucketName }}
          region: ${{ parameters.region }}
          environment: ${{ parameters.environment }}
          owner: ${{ parameters.owner }}
          versioning: ${{ parameters.versioning }}

    - id: publish
      name: Publish Repository
      action: publish:github
      input:
        repoUrl: github.com?owner=Abhi0312-eve&repo=${{ parameters.bucketName }}-terraform
        description: Terraform generated by Backstage for AWS S3
        defaultBranch: main
        repoVisibility: public

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}

      - title: Terraform Workflow
        url: ${{ steps.publish.output.remoteUrl }}/actions
